
# Source: journey-v2/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: journey-v2
    app.kubernetes.io/instance: mydemo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: journey-v2
    app.kubernetes.io/part-of: de
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: journey-v2-0.1.0
  name: mydemo-journey-v2
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: mydemo
    app.kubernetes.io/name: journey-v2
  type: ClusterIP
---
# Source: journey-v2/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: journey-v2
    app.kubernetes.io/instance: mydemo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: journey-v2
    app.kubernetes.io/part-of: de
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: journey-v2-0.1.0
  name: mydemo-journey-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mydemo
      app.kubernetes.io/name: journey-v2
  template:
    metadata:
      annotations: null
      labels:
        app.kubernetes.io/instance: mydemo
        app.kubernetes.io/name: journey-v2
    spec:
      containers:
      - env:
        - name: ZDE_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EDQ_AUTH_TOKEN
          value: a8bd4225-7149-4df4-80db-f062947f1c37
        - name: HMAC_PASSWORD
          value: 2GBFb1ebbiHM2XYK
        - name: HMAC_USERNAME
          value: zoral
        - name: Z_BDWH_SCRIPT
          value: https://bds.dev.zde.jaja.co.uk/script?systemCode=04D27467-2275-4B04-8A35-CBA688DD22C9
        image: 492071692632.dkr.ecr.eu-west-2.amazonaws.com/zde/journey-nbo:1.0.450-v2
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 80
        name: journey-v2
        ports:
        - containerPort: 80
          name: service
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 80
        volumeMounts: null
      serviceAccountName: default
      volumes: null
---
# Source: journey-v2/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: route53
    certmanager.k8s.io/cluster-issuer: letsencrypt-default
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/component: journey-v2
    app.kubernetes.io/instance: mydemo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: journey-v2
    app.kubernetes.io/part-of: de
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: journey-v2-0.1.0
  name: mydemo-journey-v2
spec:
  rules:
  - host: journey-v2.dev.zde.jaja.co.uk
    http:
      paths:
      - backend:
          serviceName: mydemo-journey-v2
          servicePort: 80
        path: /
  tls:
  - hosts:
    - journey-v2.dev.zde.jaja.co.uk
    secretName: zde-tls-secret

