
{{- define "libchart.secret.tpl" -}}
{{- if .Values.envRenderSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "service.fullname" . }}-env
  labels:
    {{- include "service.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.envRenderSecret }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end -}}
{{- end }}

{{- end -}}
{{- define "libchart.secret" -}}
{{- include "libchart.util.merge" (append . "libchart.secret.tpl") -}}
{{- end -}}