{{- define "libchart.serviceaccount.tpl" -}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "service.labels" . | nindent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ include "service.serviceAccountName" . }}
{{- end }}

{{- end -}}
{{- define "libchart.serviceaccount" -}}
{{- include "libchart.util.merge" (append . "libchart.serviceaccount.tpl") -}}
{{- end -}}