component: pagebuilder
serviceAccount:
  create: false
  name: zde-service
image:
  repository: zoralft/generic-zdj-page-builder
  tag: 0.0.8
  pullPolicy: Always
  pullSecrets: []

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: http
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: http
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
replicas: 1
podPort:
  name: service
  port: 80

env: {}
envValueFrom: {}
envFromSecret: {}
envRenderSecret: {}

service:
  portName: http
  fullName: journey-v2
  port: 80
  targetPort: 80
  labels: {}

ingress:
  enabled: true
  # Values can be templated
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-default"
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: route53
  labels: {}
  path: /
  hosts:
    - journey-v2.dev.zde.jaja.co.uk
  ## Extra paths to prepend to every host configuration. This is useful when working with annotation based services.
  extraPaths: []
  # - path: /*
  #   backend:
  #     serviceName: ssl-redirect
  #     servicePort: use-annotation
  tls:
   - secretName: zde-tls-secret
     hosts:
       - journey-v2.dev.zde.jaja.co.uk